### ISSUE TITLE
Reports folder is missing

### ISSUE THREAD

**Issue by larryg01** [john-doherty/selenium-cucumber-js#1]
When code checked out and installed the reports is missing so testrun fails

**Comment by john-doherty** [comment]
@larryg01 please can you retest this?

**Comment by larryg01** [comment]
I have re-downloaded and install the package again and its all good now, although the first time I ran the test i got the "function timed out after 10000 milliseconds" error but ran it again and it passed ok. I think you should look into the hardcoded timeout

**Comment by john-doherty** [comment]
Thanks @larryg01, I'll look into it
