### ISSUE TITLE
Before/After handlers

### ISSUE THREAD

**Issue by moogjet** [john-doherty/selenium-cucumber-js#10]
Hi,

I've not been able to get the Before/After Feature or Scenario event handlers working in my step definitions.

```
    this.BeforeFeature(/^Feature Name$/, function () {
        return helpers.loadPage('http://localhost/login').then(function() {
            return page.login.login(shared.testData.username, shared.testData.password);
        });
    });

```
Is there an example of how to do this? The above code works in a When - is something like this possible in a Before/After?

Thanks!

**Comment by john-doherty** [comment]
Hi @moogjet, apologies for the slow response. I've updated the readme to include example of [before/after](https://github.com/john-doherty/selenium-cucumber-js#event-handlers) hooks
