### ISSUE TITLE
Cucumber 2.x

### ISSUE THREAD

**Issue by bricas** [john-doherty/selenium-cucumber-js#11]
Jus a question and not a bug per se, but, are there any plans to support Cucumber.js 2.x?

**Comment by john-doherty** [comment]
No plans at the moment. What value does it add?

**Comment by bricas** [comment]
At a high level, essentially nothing, but 2.x is the actively developed branch.

There are a number of major coding changes, though (see [changelog](https://github.com/cucumber/cucumber-js/blob/master/CHANGELOG.md)), which means it also not really a trivial change either.

I just worry about things going stale and unsupported.

**Comment by john-doherty** [comment]
Yes, that's a good point. I've not had chance to look over v2. I wonder if it's possible to support both versions, allowing users the choice of syntax and removing the need to force them to upgrade.

**Comment by bricas** [comment]
Again, I don't have any good answers here, but, what about the latest Cucumber.js 1.x version in the interim? Shouldn't be a huge jump from 1.2.2 to 1.3.3, I wouldn't think?
