### ISSUE TITLE
chromedriver is out of date

### ISSUE THREAD

**Issue by leggebroten** [john-doherty/selenium-cucumber-js#14]
Hi,

The chromedriver you have in your node_modules is .25 which does not support async/await.
The most recent version is .30.

-Lee

**Comment by john-doherty** [comment]
Hi @leggebroten, thanks for raising this. I managed to upgrade chromedriver to version 2.28.0, anything higher than that broke the build. Please let me know if this works, I will bump to .30 when I have more time to test/tweak.

**Comment by leggebroten** [comment]
Awesome.  You rock
