### ISSUE TITLE
feature request: command line option to disable report types

### ISSUE THREAD

**Issue by bricas** [john-doherty/selenium-cucumber-js#15]
We use our test suite as a health-checking framework ("are services a, b, and c online?") which runs every 3 minutes.

While the json report output is useful for us (jenkins integration via the [Cucumber Test Result Plugin)](https://wiki.jenkins.io/display/JENKINS/Cucumber+Test+Result+Plugin), neither the junit nor the html reports will ever been looked at.

While this sounds innocuous, the html report generator will write out the screenshots to disk on every failure. These screenshots will never be cleaned up between test suite runs resulting in a bunch of stray files over time.

My work around is to simply delete the screenshots directory as an extra step in our jenkins job, but it would be nice if we could disable the output completely. 

Thanks again for this great framework.

**Comment by john-doherty** [comment]
Hi @bricas, thanks for your kind words ;)

The cucumber report files are overwritten each time so should not be a problem. I've added an `-n` switch to disable the capturing of screenshots when an error is encountered. 

I'll check in/publish the changes now. Let me know how you get on.

**Comment by bricas** [comment]
I think perhaps I've not stated the issue quite as I wanted. :)

Firstly: I love screenshots. 

The json output actually embeds the screenshots (which is very handy for browsing failures in our Jenkins setup).

But, the issue is that the Html report saves screenshot files to reports/screenshots which end up hanging around over time. 

I want the embedded screenshots in json, but not the reports/screeenshots dir that gets filled up by the Html report.

I've added an `rm reports/screenshots` line to my Jenkins task but it's a tad annoying. 

Anywho! Thanks for the speedy response :)

**Comment by john-doherty** [comment]
Ah, I see. Ok, thanks for explaining it more detail.

**Comment by john-doherty** [comment]
Ok. I have updated the html report component to the latest version which inlines HTML images by default so they are never saved to disk. Sorry for the mix up.

**Comment by bricas** [comment]
That's perfect! Thanks so much! :)
