### ISSUE TITLE
How do i execute a single specific .feature file using selenium-cucumber-js

### ISSUE THREAD

**Issue by guptarajatkn** [john-doherty/selenium-cucumber-js#2]
Currently to run my automation tests i am using **node index.js -s .\step-definitions -r .\reports\** 
to run a specific feature i need to add a tag and then use it in above command with a -t arg

but i have existing set of feature files where I donot have proper tags, is there some way we can specify a single .feature file in the above command to execute the tests as we can do with cucumber-js
eg :  providing : .\features\login.feature

**Comment by john-doherty** [comment]
Hi @guptarajatkn. This was not possible but a good idea so I've added it as a command line [-f switch](https://github.com/john-doherty/selenium-cucumber-js#options). 

You will need to update your version by running the following:

```
npm uninstall selenium-cucumber-js --save
npm install selenium-cucumber-js --save
```

You then add the path to your feature, for example:

```
node index.js -s .\step-definitions -r .\reports -f .\features\login.feature
```

Let me know if this works for you.

**Comment by guptarajatkn** [comment]
Great. It Worked. 
Really Cool Thanks :)
