### ISSUE TITLE
local node packages cause version mis-match errors

### ISSUE THREAD

**Issue by leggebroten** [john-doherty/selenium-cucumber-js#20]
Hi,

Thanks again for the shell.
The problem I've run into a couple times is that the two NPM packages you have in a local node_modules are of different (older) versions than what I'm using, which results in mis-matched objects.

Everything works fine if I delete your package-local node_modules.

**Comment by john-doherty** [comment]
Hi @leggebroten, I've removed it and checked in a fix. Sorry I've not managed to review your pull requests, I will do that this weekend.

**Comment by leggebroten** [comment]
Thx!
