### ISSUE TITLE
New config properties should match command line help

### ISSUE THREAD

**Issue by john-doherty** [john-doherty/selenium-cucumber-js#26]
For consistency, the [config properties](https://github.com/john-doherty/selenium-cucumber-js/blob/master/index.js#L16) from the newly created `selenium-cucumber-js.json` file should match those in the [README](https://github.com/john-doherty/selenium-cucumber-js/blob/master/index.js#L33).

**Comment by leggebroten** [comment]
Added PR

**Comment by john-doherty** [comment]
Thanks!
