### ISSUE TITLE
By any Chance Can I execute multiple Features/Scenarios in parallel

### ISSUE THREAD

**Issue by guptarajatkn** [john-doherty/selenium-cucumber-js#3]
By any Chance Can I execute multiple Features/Scenarios in parallel.

Also is there any way i can execute same feature or scenario on different browsers at once - same time.

**Comment by guptarajatkn** [comment]
Guess this would cause issue to the reporter to generate reports. So we might need to disable the report generation.

**Comment by john-doherty** [comment]
Not sure I understand what you are asking for, please can you provide a bit more context?

**Comment by john-doherty** [comment]
Closing this as not sure it's needed. Please reopen if I'm wrong.
