### ISSUE TITLE
Custom driver configurations 

### ISSUE THREAD

**Issue by Temi89** [john-doherty/selenium-cucumber-js#36]
How do I set custom web driver instances ? Do I need a configuration file where I can add desired capabilites and browser configurations . At the moment it's not clear how this is done . Is there an example ?

**Comment by Temi89** [comment]
Hi lee , is there a way to update the confit file to specify custom webdriver configurations and sessions like desired capabilities and browser config using selenium builder api ? So basically something like this ::

const driver = new webdriver.Builder()
// The "9515" is the port opened by chrome driver.
.usingServer('http://localhost:9515')
.withCapabilities({
chromeOptions: {
// Here is the path to your Electron binary.
binary: '/Path-to-Your-App.app/Contents/MacOS/Electron'

Ref link :::https://github.com/electron/electron/blob/master/docs/tutorial/using-selenium-and-webdriver.md

**Comment by Temi89** [comment]
Found a work that works . Created a config directory inside step definitions and added a before feature hooks to set global driver to my config : 


module.exports = function () {

    // add a before feature hook
    /* eslint new-cap:0*/
    this.BeforeFeature((feature) => {

        global.driver = new selenium.Builder()
        // The "9515" is the port opened by chrome driver.
            .usingServer('http://localhost:9515')
            .withCapabilities({
                chromeOptions: {
                    // Here is the path to your Electron binary.
                    // binary: '/Path-to-Your-App.app/Contents/MacOS/Electron'
                }
            })
            .forBrowser('electron')
            .build();

    });
};

**Comment by john-doherty** [comment]
Hey @Temi89, have you resolved the issue?

**Comment by Temi89** [comment]
Hey @john-doherty . Yes got it working it needed a js file in runtime dir with the driver config and also an a case statement in world.js for the additional browser

**Comment by superhero1** [comment]
@Temi89 would be nice if you share your result with the community.
