### ISSUE TITLE
New version does not install all dependencies

### ISSUE THREAD

**Issue by rudovjan** [john-doherty/selenium-cucumber-js#41]
After npm install I got

```
node ./node_modules/selenium-cucumber-js/index.js
module.js:472
    throw err;
    ^

Error: Cannot find module 'eyes.selenium'
```

I installed eyes.selenium using 

```
npm install eyes.selenium --save
```

Weirdly it eyes.selenium is listed as a dependency in this project.

**Edited:**
Oh it's listed in dev dependencies

**Comment by john-doherty** [comment]
Thanks @rudovjan, it was incorrectly listed in `devDependencies`. I've moved it to `dependencies` and pushed a new version. Please re-open this ticket if it does not resolve the issue
