### ISSUE TITLE
AfterScenario detect if scenario failed or no

### ISSUE THREAD

**Issue by vhugogarcia** [john-doherty/selenium-cucumber-js#60]
Hello friends,

anybody knows how to detect on the hook AfterScenario if it failed or no?

I tried already with: IsFailed
`if (!scenario.isFailed)
      {
        driver.call(setScore, null, 'pass').then(function(result){
          console.log('set score to pass');
        });
      }
      done();`

I had no cluck with that. 

Any idea is always welcome.

**Comment by tjl694** [comment]
I believe it should be `scenario.isFailed()`
