### ISSUE TITLE
Phantonjs doesn't work correct with Ajax

### ISSUE THREAD

**Issue by gnovitskaya** [john-doherty/selenium-cucumber-js#7]
When I run tests using Phantomjs - ajax is pending.
such settings                 
'phantomjs.cli.args': ['--web-security=false', '--ignore-ssl-errors=true', '--webdriver-loglevel=DEBUG'],
could help to resolve this issue

**Comment by john-doherty** [comment]
I'm not sure I understand the issue. Can you paste the command line params you're using?

**Comment by john-doherty** [comment]
@gnovitskaya I'm closing this as I am unable to reproduce your issue. Feel free to open another ticket with more info if the problem persists.
