### ISSUE TITLE
Pass multiple feature files via command line

### ISSUE THREAD

**Issue by khause** [john-doherty/selenium-cucumber-js#72]
I would like to pass a list of comma-separated feature files via command line.
e.g. `-f features/feature-file-1,features/feature-file-2,...,features/feature-file-n`

To my understanding, you're currently only allowed to pass in a single file or folder.

**Comment by khause** [comment]
I would like to raise a pull request for this issue but I'm unable to push a branch to this repo.

**Comment by john-doherty** [comment]
Hi @khause, you'll need to fork the project first. The process is:

1. Fork it!
2. Create your feature branch: `git checkout -b my-new-feature`
3. Commit your changes: `git commit -m 'Add some feature'`
4. Push to the branch: `git push origin my-new-feature`
5. Submit a pull request

**Comment by john-doherty** [comment]
Thanks for the PR @khause, it's now merged and published to NPM.
