### ISSUE TITLE
Selenium cucumber does not run on Mac

### ISSUE THREAD

**Issue by lucfranken** [john-doherty/selenium-cucumber-js#85]
When I run the examples I get errors of a file not found.

```terminal
$ node ./node_modules/selenium-cucumber-js/index.js
fs.js:122
    throw err;
    ^

Error: ENOENT: no such file or directory, lstat '/Users/xxx/Software/xxx/xxx/"synchronous"}''
```

The full directory is correct: /Users/xxx/Software/xxx/xxx/, tested that with cd command.

It looks like "synchronous" is added behind the path but I cannot find it in the repository.

```terminal
node -v
v11.0.0
npm -v
6.4.1
```

package.json
```
{
  "name": "xxxx",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "cucumber-js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "selenium-cucumber-js": "^1.6.2"
  },
  "dependencies": {}
}
```

**Comment by stck** [comment]
Do you still facing this issue? @lucfranken

**Comment by lucfranken** [comment]
@stck yes: Same problem still exists. Has there been any update as I don't see one?

**Comment by stck** [comment]
@lucfranken So i can't reproduce this with your environment, even with examples.
`node ./node_modules/selenium-cucumber-js/index.js -f node_modules/selenium-cucumber-js/features/buy-workwear.feature` looks fine for me w/ Node 11.0.0(x64). Can you connect to your node with [debugger](https://nodejs.org/en/docs/guides/debugging-getting-started/) and look for stacktrace?

**Comment by iTechDhaval** [comment]
> @lucfranken So i can't reproduce this with your environment, even with examples.
> `node ./node_modules/selenium-cucumber-js/index.js -f node_modules/selenium-cucumber-js/features/buy-workwear.feature` looks fine for me w/ Node 11.0.0(x64). Can you connect to your node with [debugger](https://nodejs.org/en/docs/guides/debugging-getting-started/) and look for stacktrace?

 `node ./node_modules/selenium-cucumber-js/index.js -f node_modules/selenium-cucumber-js/features/buy-workwear.feature` command also result in same error on windows and linux both environment. I have not checked it in macos.

**Comment by john-doherty** [comment]
Fixed. Min node version updated to 12
