### ISSUE TITLE
session not created: Chrome version must be between 71 and 75

### ISSUE THREAD

**Issue by whuey1992** [john-doherty/selenium-cucumber-js#90]
did a clean npm install today and started getting this issue when running selenium-cucumber tests

 SessionNotCreatedError: session not created: Chrome version must be between 71 and 75
       (Driver info: chromedriver=2.46.628411 (3324f4c8be9ff2f70a05a30ebc72ffb013e1a71e),platform=Mac OS X 10.13.6 x86_64)

**Comment by whuey1992** [comment]
Seems to not work since I am using custom driver

var webdriver = require('./node_modules/selenium-cucumber-js/node_modules/selenium-webdriver');
var chrome = require('./node_modules/selenium-cucumber-js/node_modules/selenium-webdriver/chrome');
var chromium = require('./node_modules/chromium');

module.exports = function() {

   var options = new chrome.Options();
   var capabilities = webdriver.Capabilities.chrome();
   capabilities.set("acceptInsecureCerts", true);
   options.setChromeBinaryPath(chromium.path);
   options.addArguments("--no-sandbox");
   options.addArguments("--disable-gpu");
   options.addArguments("--ignore-certificate-errors");
   options.addArguments("--headless");
   options.addArguments("--window-size=1920,1080");
   const driver = new webdriver.Builder()
    .forBrowser('chrome')
    .setChromeOptions(options)
    .withCapabilities(capabilities)
    .build();

   /* Overriding this method because of bug when using on remote service
      The method is implemented in the npm dependency, so this is a hack
      */
   driver.close = function() {
      return new Promise(function(resolve, reject) {
          resolve();
      });
   };

   return driver;
};

package.json
"chromium": "^1.0.2"
"selenium-cucumber-js": "^1.6.2",
"selenium-webdriver": "^4.0.0-alpha.1"

**Comment by whuey1992** [comment]
Seems the issue is that chromium is now at ver 76 which is no longer supported by this framework, will there be an update to make it compatible with newer versions of chrome/chromium

**Comment by george1410** [comment]
#92 resolves this issue

**Comment by john-doherty** [comment]
Thanks @george1410
